// Per-screen renderer for Sotto. screen(d) returns HTML for the active (viewAs, phase).
// Faithful port of the Claude Design prototype screens.
function btnAccent(label, onclick, extra=''){
  return `<button onclick="${onclick}" style="padding:14px;border-radius:9px;border:none;background:var(--accent);color:#fff;font-size:14px;font-weight:600;cursor:pointer;${extra}">${label}</button>`;
}
function h1(t){ return `<h1 style="margin:0;font-size:24px;font-weight:600;letter-spacing:-.01em;">${t}</h1>`; }
function sub(t){ return `<p style="margin:0 0 24px;font-size:13.5px;color:var(--dim);max-width:600px;">${t}</p>`; }

function screen(d){
  const ph=d.ph, P=d.P, L=d.L;
  if(ph==='cleared') return settling(d);
  if(ph==='rollback') return rollback(d);
  if(d.youSeller){
    if(ph==='draft') return sellerDraft(d);
    if(ph==='open'||ph==='live') return sellerMonitor(d);
    if(ph==='locked') return sellerClear(d);
    if(ph==='settled') return sellerOutcome(d);
  } else {
    if(ph==='draft') return bidderAwait(d);
    if(ph==='open' && !d.hasMyBid) return bidderSubmit(d);
    if((ph==='open'&&d.hasMyBid)||ph==='live') return bidderSealed(d);
    if(ph==='locked') return bidderLocked(d);
    if(ph==='settled') return bidderOutcome(d);
  }
  return '';
}

function sellerDraft(d){
  const L=d.L;
  const counterparty=(name,desk)=>`<div style="display:flex;align-items:center;gap:11px;padding:10px 12px;background:var(--panel2);border:1px solid var(--line2);border-radius:8px;"><span style="width:18px;height:18px;border-radius:5px;background:var(--accent);display:flex;align-items:center;justify-content:center;flex:none;">${CHECK()}</span><span style="font-size:13.5px;font-weight:600;">${name}</span><span style="margin-left:auto;font-size:11px;color:var(--faint);">desk · ${desk}</span></div>`;
  const trow=(l,v,c='')=>`<div class="row-split" style="padding:18px 0;border-bottom:1px solid var(--line);"><span style="font-size:13px;color:var(--dim);">${l}</span><span style="font-size:14px;font-weight:600;${c}">${v}</span></div>`;
  return `<div class="fade"><div style="display:flex;align-items:baseline;gap:12px;margin-bottom:4px;">${h1('Create '+L.listing)}<span style="font-size:13px;color:var(--dim);">${d.winRuleLine}</span></div>
    ${sub('You are the clearing party. Define the block, set a '+d.reserveWordLower+', and invite counterparties. Their bids stay sealed until you clear.')}
    <div style="display:grid;grid-template-columns:1fr 360px;gap:22px;align-items:start;">
      <div class="panel" style="padding:6px 22px;">${trow('Instrument','U.S. Treasury Bill · 26-week')}${trow('Face value',d.faceFmt,"font-family:'IBM Plex Mono',monospace;")}${trow(L.reserveWord,d.reserveFmt,"font-family:'IBM Plex Mono',monospace;color:var(--accent-text);")}<div class="row-split" style="padding:18px 0;"><span style="font-size:13px;color:var(--dim);">Deadline</span><span style="font-size:14px;font-weight:600;">Today · 14:30 ET</span></div></div>
      <div style="display:flex;flex-direction:column;gap:18px;">
        <div class="panel" style="padding:18px;"><div class="row-split" style="margin-bottom:14px;"><span class="caps">${L.invite}</span><span style="font-size:11px;color:var(--dim);">2 selected</span></div><div style="display:flex;flex-direction:column;gap:9px;">${counterparty('Meridian Capital','MER')}${counterparty('Halcyon Asset Mgmt','HAL')}</div></div>
        <div style="background:var(--accent-dim);border:1px solid var(--accent-line);border-radius:12px;padding:16px 18px;"><div style="font-size:11px;font-weight:600;color:var(--accent-text);margin-bottom:10px;">What becomes visible to whom</div><ul style="margin:0;padding:0;list-style:none;display:flex;flex-direction:column;gap:8px;"><li style="font-size:12.5px;line-height:1.4;">Terms &amp; ${d.reserveWordLower} — <span style="color:var(--dim);">all invited counterparties</span></li><li style="font-size:12.5px;line-height:1.4;">Each bid — <span style="color:var(--dim);">its bidder + you (clearing party) only</span></li><li style="font-size:12.5px;line-height:1.4;">No counterparty sees another's bid or identity</li></ul><div style="margin-top:13px;">${inspector(d.termsViewers,{label:'Preview need-to-know',footer:'Bidders never see each other. Enforced on Canton.'})}</div></div>
        ${btnAccent('Publish listing &amp; open bidding', "goPhase('open')", 'width:100%;')}
      </div></div></div>`;
}

function sellerMonitor(d){
  const b=d.b, respCount=(b.A?1:0)+(b.B?1:0);
  const rows=[['MER',d.P.A,b.A],['HAL',d.P.B,b.B]].map(([code,name,bid])=>{
    const inner = bid
      ? `<div style="flex:1;display:flex;align-items:center;gap:14px;"><div class="hatch" style="flex:1;display:flex;align-items:center;gap:12px;padding:11px 14px;border-radius:8px;">${SEAL()}<span style="font-size:12.5px;font-weight:500;color:var(--dim);">Sealed bid received — held by the network</span></div><span class="mono" style="font-size:12px;color:var(--faint);">${bid.t} ET</span></div>`
      : `<div style="flex:1;display:flex;align-items:center;gap:10px;"><span style="width:7px;height:7px;border-radius:50%;border:1.5px solid var(--faint);"></span><span style="font-size:12.5px;color:var(--faint);">Awaiting response</span></div>`;
    return `<div class="panel" style="display:flex;align-items:center;gap:16px;padding:18px 20px;"><span style="width:36px;height:36px;border-radius:8px;background:var(--panel2);border:1px solid var(--line2);display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;color:var(--dim);flex:none;">${code}</span><div style="min-width:160px;"><div style="font-size:14px;font-weight:600;">${name}</div><div style="font-size:11.5px;color:var(--faint);">Treasury desk · ${code}</div></div>${inner}<div style="margin-left:auto;">${inspector([{name,role:'bidder'},d.sellerV],{label:'Seen by 2',align:'right',footer:'Sealed to you until you clear after the deadline.'})}</div></div>`;
  }).join('');
  return `<div class="fade"><div style="display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:20px;"><div>${h1('Sealed responses')}<p style="margin:4px 0 0;font-size:13.5px;color:var(--dim);">${respCount} of 2 invited counterparties have responded. Amounts stay sealed — even to you — until the deadline closes the envelope.</p></div><div style="text-align:right;"><div style="font-size:11px;color:var(--faint);letter-spacing:.04em;text-transform:uppercase;">Closes in</div><div class="mono" style="font-size:20px;font-weight:600;color:var(--accent-text);">00:27:14</div></div></div>
    <div style="display:flex;flex-direction:column;gap:12px;">${rows}</div>
    <div style="margin-top:18px;display:flex;align-items:center;gap:14px;padding:15px 18px;border:1px dashed var(--line2);border-radius:12px;">${SEAL('var(--faint)',16)}<span style="font-size:13px;color:var(--dim);">Bids unseal to you only when the deadline closes. Clearing is locked until then.</span><button disabled style="margin-left:auto;padding:11px 18px;border-radius:8px;border:1px solid var(--line2);background:transparent;color:var(--faint);font-size:13px;font-weight:600;cursor:not-allowed;">Clearing unlocks at the deadline</button></div></div>`;
}

function sellerClear(d){
  const r=d.r, rows=r.arr.map((x,i)=>{
    const best=i===0&&!r.tie, short=x.escrow<x.amount;
    const badges=(best?'<span style="font-size:9.5px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;padding:2px 7px;border-radius:4px;background:var(--accent);color:#fff;">Best</span>':'')+(short?'<span style="font-size:9.5px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;padding:2px 7px;border-radius:4px;background:var(--bad-dim);color:var(--bad-text);">Escrow short</span>':'');
    return `<div style="display:grid;grid-template-columns:44px 1fr 200px 160px 130px;align-items:center;padding:17px 20px;border-top:${i===0?'none':'1px solid var(--line)'};background:${best?'var(--accent-dim)':'transparent'};">
      <span class="mono" style="font-size:14px;font-weight:700;color:${best?'var(--accent-text)':'var(--faint)'};">${i+1}</span>
      <div style="display:flex;align-items:center;gap:11px;min-width:0;"><span style="font-size:14.5px;font-weight:600;">${d.P[x.id]}</span>${badges}</div>
      <span class="mono" style="font-size:15px;font-weight:600;text-align:right;color:${best?'var(--accent-text)':'var(--text)'};">${fmt(x.amount)}</span>
      <span class="mono" style="font-size:13px;text-align:right;color:${short?'var(--bad-text)':'var(--dim)'};">${fmt(x.escrow)}</span>
      <div style="display:flex;justify-content:flex-end;">${inspector([{name:d.P[x.id],role:'bidder'},d.sellerV],{label:'Seen by 2',align:'right',footer:'This bid is visible only to its bidder and you.'})}</div></div>`;
  }).join('');
  const tieBanner=r.tie?`<div style="display:flex;align-items:center;gap:11px;margin-bottom:14px;padding:12px 16px;border-radius:10px;background:var(--warn-dim);border:1px solid var(--warn);"><span style="font-size:12.5px;font-weight:600;color:var(--warn);">Tie detected.</span><span style="font-size:12.5px;color:var(--dim);">Two bids are identical. Tie-break: earliest sealed submission clears.</span></div>`:'';
  const singleBanner=d.isSingle?`<div style="display:flex;align-items:center;gap:11px;margin-bottom:14px;padding:12px 16px;border-radius:10px;background:var(--accent-dim);border:1px solid var(--accent-line);"><span style="font-size:12.5px;font-weight:600;color:var(--accent-text);">Single bidder.</span><span style="font-size:12.5px;color:var(--dim);">One sealed bid received. It clears if it meets the ${d.reserveWordLower}.</span></div>`:'';
  return `<div class="fade"><div style="display:flex;align-items:center;gap:11px;margin-bottom:6px;">${h1('Clearing view')}<span style="display:inline-flex;align-items:center;gap:6px;padding:4px 10px;border-radius:999px;background:var(--accent-dim);color:var(--accent-text);font-size:11px;font-weight:600;">${LOCK('currentColor',11)} Clearing party · authorized</span></div>
    <p style="margin:0 0 22px;font-size:13.5px;color:var(--dim);">Deadline passed. Sealed bids are now visible to you alone. ${d.winRuleLine}.</p>${tieBanner}${singleBanner}
    <div class="panel" style="overflow:hidden;"><div style="display:grid;grid-template-columns:44px 1fr 200px 160px 130px;padding:12px 20px;border-bottom:1px solid var(--line);background:var(--panel2);"><span class="caps">#</span><span class="caps">Counterparty</span><span class="caps" style="text-align:right;">Sealed bid</span><span class="caps" style="text-align:right;">Escrow</span><span></span></div>${rows}</div>
    <div style="margin-top:22px;display:flex;align-items:center;gap:20px;padding:20px 24px;background:var(--panel);border:1px solid var(--accent-line);border-radius:12px;"><div><div class="caps" style="margin-bottom:5px;">Clears to</div><div style="display:flex;align-items:baseline;gap:12px;"><span style="font-size:15px;font-weight:600;">${d.winnerName}</span><span class="mono" style="font-size:26px;font-weight:600;color:var(--accent-text);">${d.winnerAmountFmt}</span></div></div><div style="flex:1;"></div><div style="font-size:11.5px;color:var(--dim);display:flex;align-items:center;gap:7px;">${LOCK('var(--accent-text)',13)} Only the clearing party can clear</div>
    <button onclick="doClear()" style="padding:15px 26px;border-radius:9px;border:none;background:var(--accent);color:#fff;font-size:14.5px;font-weight:700;cursor:pointer;white-space:nowrap;animation:pulseR 2.4s infinite;">${L_clearLabel(d)} →</button></div></div>`;
}
function L_clearLabel(d){ return d.L.clearWord+' to best bid · '+d.winnerAmountFmt; }

function settling(d){
  return `<div style="max-width:760px;margin:30px auto 0;"><div style="text-align:center;margin-bottom:30px;"><div style="display:inline-flex;align-items:center;gap:8px;padding:5px 13px;border-radius:999px;background:var(--accent-dim);color:var(--accent-text);font-size:12px;font-weight:600;margin-bottom:14px;"><span style="width:7px;height:7px;border-radius:50%;background:currentColor;animation:pulseR 1.4s infinite;"></span>Settling</div>${h1('Atomic delivery versus payment')}<p style="margin:6px 0 0;font-size:13.5px;color:var(--dim);">Asset and cash exchange in one indivisible step. Both legs settle, or neither does.</p></div>
    <div style="position:relative;display:grid;grid-template-columns:1fr 130px 1fr;align-items:stretch;">
      <div class="panel" style="padding:22px 20px;animation:legL .9s ease both;"><div class="caps" style="margin-bottom:10px;">Leg 1 · Asset</div><div style="font-size:15px;font-weight:600;margin-bottom:4px;">T-Bill block · ${d.faceFmt}</div><div style="font-size:12.5px;color:var(--dim);">Acme Treasury → ${d.winnerName}</div></div>
      <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;"><div style="position:absolute;top:50%;left:-1px;right:-1px;height:2px;background:var(--accent-line);transform:translateY(-50%);"></div><div style="z-index:2;width:54px;height:54px;border-radius:14px;background:var(--accent);display:flex;align-items:center;justify-content:center;animation:lockSpin .7s ease both;box-shadow:0 0 0 6px var(--accent-dim);">${LOCK('#fff',24)}</div><span style="z-index:2;font-size:9.5px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--accent-text);background:var(--bg);padding:0 6px;">Atomic</span></div>
      <div class="panel" style="padding:22px 20px;text-align:right;animation:legR .9s ease both;"><div class="caps" style="margin-bottom:10px;">Leg 2 · Cash</div><div class="mono" style="font-size:15px;font-weight:600;margin-bottom:4px;">${d.winnerAmountFmt}</div><div style="font-size:12.5px;color:var(--dim);">${d.winnerName} → Acme Treasury</div></div></div>
    <div style="margin-top:18px;height:4px;border-radius:3px;background:var(--line);overflow:hidden;"><div style="height:100%;width:100%;background:var(--accent);transform-origin:left;animation:barGrow 2.5s linear both;"></div></div>
    <div class="mono" style="margin-top:10px;text-align:center;font-size:12px;color:var(--faint);">Binding both legs · settlement ${d.settleId}</div></div>`;
}

function rollback(d){
  return `<div style="max-width:760px;margin:10px auto 0;"><div style="text-align:center;margin-bottom:26px;"><div style="display:inline-flex;align-items:center;gap:8px;padding:5px 13px;border-radius:999px;background:var(--bad-dim);color:var(--bad-text);font-size:12px;font-weight:600;margin-bottom:14px;">↺ Rolled back</div>${h1('Settlement did not complete')}<p style="margin:6px auto 0;max-width:460px;font-size:13.5px;color:var(--dim);">${rollbackReason(d)} Because settlement is atomic, neither leg moved.</p></div>
    <div style="display:grid;grid-template-columns:1fr 130px 1fr;align-items:stretch;">
      <div class="panel" style="padding:22px 20px;opacity:.7;"><div class="caps" style="margin-bottom:10px;">Leg 1 · Asset</div><div style="font-size:15px;font-weight:600;margin-bottom:4px;text-decoration:line-through;text-decoration-color:var(--bad);">T-Bill block · ${d.faceFmt}</div><div style="font-size:12px;color:var(--bad-text);">Not delivered · retained by seller</div></div>
      <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;position:relative;"><div style="position:absolute;top:50%;left:-1px;right:-1px;height:2px;background:var(--bad);transform:translateY(-50%);opacity:.5;"></div><div style="z-index:2;width:54px;height:54px;border-radius:14px;background:var(--bad-dim);border:1.5px solid var(--bad);display:flex;align-items:center;justify-content:center;"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--bad-text)" stroke-width="2.2"><path d="M18 6 6 18M6 6l12 12"></path></svg></div><span style="z-index:2;margin-top:9px;font-size:9.5px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--bad-text);background:var(--bg);padding:0 6px;">Neither leg</span></div>
      <div class="panel" style="padding:22px 20px;text-align:right;opacity:.7;"><div class="caps" style="margin-bottom:10px;">Leg 2 · Cash</div><div class="mono" style="font-size:15px;font-weight:600;margin-bottom:4px;text-decoration:line-through;text-decoration-color:var(--bad);">${d.winnerAmountFmt}</div><div style="font-size:12px;color:var(--bad-text);">Not transferred · escrow returned</div></div></div>
    <div style="margin-top:20px;display:flex;align-items:center;gap:12px;padding:14px 18px;background:var(--panel2);border:1px solid var(--line);border-radius:10px;"><span style="font-size:12.5px;color:var(--dim);">State is exactly as before the clear — controlled, not a crash.</span>${d.isSeller?'<button onclick="resetDemo()" style="margin-left:auto;padding:8px 14px;border-radius:7px;border:1px solid var(--accent-line);background:var(--accent-dim);color:var(--accent-text);font-size:12px;font-weight:600;cursor:pointer;">Reset demo</button>':''}</div></div>`;
}
function rollbackReason(d){ return d.wb && d.wb.escrow<d.wb.amount ? d.winnerName+"'s escrow ("+fmt(d.wb.escrow)+") fell short of its bid ("+d.winnerAmountFmt+")." : 'The winning bid could not be funded in full.'; }

function sellerOutcome(d){
  return `<div style="max-width:840px;margin:0 auto;"><div style="display:flex;align-items:center;gap:11px;margin-bottom:6px;"><span style="width:30px;height:30px;border-radius:8px;background:var(--good-dim);display:flex;align-items:center;justify-content:center;"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--good)" stroke-width="2.6"><path d="M20 6L9 17l-5-5"></path></svg></span>${h1('Settled · block cleared')}</div>
    <p style="margin:0 0 24px;font-size:13.5px;color:var(--dim);">The block was delivered and cash received in a single atomic settlement.</p>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;"><div class="panel" style="padding:22px;"><div class="caps" style="margin-bottom:8px;">${d.L.priceWord}</div><div class="mono" style="font-size:30px;font-weight:600;color:var(--good-text);margin-bottom:14px;">${d.winnerAmountFmt}</div><div>${inspector([d.sellerV,{name:d.winnerName,role:'winner',accent:true}],{label:'Seen by 2',denied:d.loserName,footer:'The losing bidder never learns the cleared price.'})}</div></div>
      <div class="panel" style="padding:22px;display:flex;flex-direction:column;gap:14px;"><div class="row-split"><span style="font-size:13px;color:var(--dim);">Cleared to</span><span style="font-size:14px;font-weight:600;">${d.winnerName}</span></div><div class="row-split"><span style="font-size:13px;color:var(--dim);">Cash received</span><span class="mono" style="font-size:14px;font-weight:600;color:var(--good-text);">+${d.winnerAmountFmt}</span></div><div class="row-split"><span style="font-size:13px;color:var(--dim);">Asset delivered</span><span style="font-size:14px;font-weight:600;">T-Bill block · ${d.faceFmt}</span></div><div class="row-split" style="padding-top:12px;border-top:1px solid var(--line);"><span style="font-size:13px;color:var(--dim);">Settlement</span><span class="mono" style="font-size:13px;font-weight:600;color:var(--good-text);">DvP · atomic ✓</span></div></div></div>
    <div style="margin-top:16px;display:flex;align-items:center;gap:12px;padding:14px 18px;background:var(--panel2);border:1px solid var(--line);border-radius:10px;"><span class="mono" style="font-size:12px;color:var(--faint);">${d.settleId}</span><span style="font-size:12.5px;color:var(--dim);">Both legs bound — no partial transfer was ever possible.</span><button onclick="resetDemo()" style="margin-left:auto;padding:8px 14px;border-radius:7px;border:1px solid var(--line2);background:transparent;color:var(--dim);font-size:12px;font-weight:600;cursor:pointer;">↺ Reset demo</button></div></div>`;
}

function bidderAwait(d){
  return `<div style="max-width:520px;margin:60px auto 0;text-align:center;"><div style="width:54px;height:54px;border-radius:14px;background:var(--panel);border:1px solid var(--line2);display:flex;align-items:center;justify-content:center;margin:0 auto 18px;"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--faint)" stroke-width="1.8"><circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path></svg></div><h1 style="margin:0 0 8px;font-size:21px;font-weight:600;">No active auction</h1><p style="margin:0;font-size:13.5px;color:var(--dim);">Awaiting a listing from the clearing party. When the block opens, you'll be invited to submit a sealed bid.</p></div>`;
}

function bidderSubmit(d){
  return `<div class="fade"><div style="display:flex;align-items:baseline;gap:12px;margin-bottom:6px;">${h1('Submit sealed '+d.bidVerbLower)}<span style="font-size:13px;color:var(--dim);">as ${d.myName}</span></div>
    <p style="margin:0 0 24px;font-size:13.5px;color:var(--dim);">Your bid is sealed the moment you submit. Visible only to you and the clearing party — no other counterparty can ever see it.</p>
    <div style="display:grid;grid-template-columns:1fr 340px;gap:22px;align-items:start;">
      <div class="panel" style="padding:24px;"><div style="margin-bottom:20px;"><label style="display:block;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--faint);margin-bottom:9px;">Your ${d.bidVerbLower} (total consideration)</label><div style="display:flex;align-items:center;gap:2px;background:var(--bg);border:1px solid var(--accent-line);border-radius:9px;padding:0 16px;"><span class="mono" style="font-size:22px;font-weight:600;color:var(--dim);">$</span><input id="bidInput" type="text" value="${d.myId==='A'?'24,812,500':'24,790,000'}" style="flex:1;background:transparent;border:none;outline:none;color:var(--text);font-family:'IBM Plex Mono',monospace;font-size:22px;font-weight:600;padding:15px 6px;"></div><div class="row-split" style="margin-top:8px;"><span style="font-size:11.5px;color:var(--faint);">${d.L.reserveWord} ${d.reserveFmt}</span><span style="font-size:11.5px;color:var(--faint);">Face ${d.faceFmt}</span></div></div>
        <div style="margin-bottom:22px;"><label style="display:block;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--faint);margin-bottom:9px;">Cash escrowed</label><div class="panel2" style="display:flex;align-items:center;gap:12px;padding:14px 16px;">${LOCK('var(--accent-text)',16)}<span style="font-size:13.5px;color:var(--dim);">Escrowed in full for the bid amount — released to you automatically if you do not win.</span></div></div>
        <button onclick="submitBid()" style="width:100%;padding:15px;border-radius:9px;border:none;background:var(--accent);color:#fff;font-size:14.5px;font-weight:700;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:9px;">${LOCK('#fff',16)} Seal &amp; submit ${d.bidVerbLower}</button></div>
      <div style="display:flex;flex-direction:column;gap:16px;"><div class="panel" style="padding:18px;"><div class="caps" style="margin-bottom:14px;">Competition</div><div style="display:flex;align-items:center;gap:13px;margin-bottom:6px;"><span class="mono" style="font-size:28px;font-weight:600;">2</span><span style="font-size:13px;color:var(--dim);line-height:1.35;">counterparties<br>invited to bid</span></div><p style="margin:12px 0 0;font-size:12px;color:var(--faint);line-height:1.5;">Their count is shown to confirm a competitive process. Their identities and amounts are never disclosed to you.</p></div>
        <div style="background:var(--accent-dim);border:1px solid var(--accent-line);border-radius:12px;padding:16px 18px;"><div style="display:flex;align-items:center;gap:9px;margin-bottom:8px;">${LOCK('var(--accent-text)',15)}<span style="font-size:12.5px;font-weight:600;color:var(--accent-text);">Sealed on submission</span></div><p style="margin:0;font-size:12px;color:var(--dim);line-height:1.5;">Visible only to you and Acme Treasury (clearing party). Enforced by the network, not a middleman.</p></div></div></div></div>`;
}

function bidderSealed(d){
  const own = d.hasMyBid
    ? `<div class="panel" style="border:1.5px solid var(--accent-line);padding:22px;position:relative;"><div class="row-split" style="margin-bottom:16px;"><span style="font-size:10px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:var(--accent-text);">Your bid</span><span style="display:inline-flex;align-items:center;gap:6px;font-size:11px;font-weight:600;color:var(--good-text);background:var(--good-dim);padding:3px 9px;border-radius:999px;"><span style="width:6px;height:6px;border-radius:50%;background:currentColor;"></span>Sealed · accepted</span></div><div class="mono" style="font-size:34px;font-weight:600;letter-spacing:-.01em;margin-bottom:18px;">${d.myBidFmt}</div><div style="display:flex;flex-direction:column;gap:11px;padding-top:16px;border-top:1px solid var(--line);"><div class="row-split"><span style="font-size:12.5px;color:var(--dim);">Cash escrowed</span><span class="mono" style="font-size:13px;font-weight:600;">${d.myEscrowFmt}</span></div><div class="row-split"><span style="font-size:12.5px;color:var(--dim);">Sealed at</span><span class="mono" style="font-size:13px;color:var(--dim);">${d.myBidTime} ET</span></div></div><div style="margin-top:16px;">${inspector([{name:d.myName,role:'bidder',you:true},d.sellerV],{label:'Who can see this bid',denied:'Other invited counterparties',footer:'Sealed on submission. Visible only to you and the clearing party.'})}</div></div>`
    : `<div class="panel" style="padding:22px;display:flex;flex-direction:column;justify-content:center;gap:8px;"><span class="caps">Your bid</span><span style="font-size:16px;font-weight:600;color:var(--dim);">No bid submitted</span></div>`;
  return `<div class="fade"><div style="display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:22px;"><div>${h1('Your sealed position')}<p style="margin:4px 0 0;font-size:13.5px;color:var(--dim);">Viewing as ${d.myName}. You see your own bid in full and nothing of anyone else's.</p></div><button onclick="setState({compare:true})" style="display:flex;align-items:center;gap:8px;padding:10px 15px;border-radius:8px;border:1px solid var(--accent-line);background:var(--accent-dim);color:var(--accent-text);font-size:12.5px;font-weight:600;cursor:pointer;">Open split view →</button></div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">${own}
      <div class="panel" style="padding:22px;overflow:hidden;"><div class="row-split" style="margin-bottom:16px;"><span class="caps">Other counterparties</span><span style="font-size:11px;color:var(--faint);">1 other invited</span></div><div class="hatch" style="display:flex;align-items:center;gap:16px;padding:20px;border-radius:10px;"><div style="width:42px;height:42px;border-radius:10px;background:var(--panel);border:1px solid var(--line2);display:flex;align-items:center;justify-content:center;flex:none;">${LOCK('var(--faint)',20)}</div><div><div class="mono" style="font-size:14px;font-weight:600;color:var(--dim);letter-spacing:.06em;">•••••••••••</div><div style="font-size:12px;color:var(--faint);margin-top:3px;">Not disclosed to you</div></div></div><p style="margin:16px 0 0;font-size:12.5px;color:var(--faint);line-height:1.5;">Their bid and identity are sealed by the network. This is by design — not missing data, not pending.</p></div></div></div>`;
}

function bidderLocked(d){
  return `<div style="max-width:560px;margin:40px auto 0;text-align:center;"><div style="width:54px;height:54px;border-radius:14px;background:var(--warn-dim);display:flex;align-items:center;justify-content:center;margin:0 auto 18px;">${LOCK('var(--warn)',24)}</div><h1 style="margin:0 0 8px;font-size:21px;font-weight:600;">Bidding closed</h1><p style="margin:0 0 22px;font-size:13.5px;color:var(--dim);">The deadline has passed. Awaiting clearing by Acme Treasury. Your sealed bid stands.</p>${d.hasMyBid?`<div style="display:inline-flex;align-items:center;gap:14px;padding:14px 20px;background:var(--panel);border:1px solid var(--line);border-radius:11px;"><span style="font-size:12.5px;color:var(--dim);">Your sealed bid</span><span class="mono" style="font-size:17px;font-weight:600;">${d.myBidFmt}</span></div>`:''}</div>`;
}

function bidderOutcome(d){
  if(d.myIsWinner) return `<div style="max-width:680px;margin:10px auto 0;text-align:center;"><div style="width:52px;height:52px;border-radius:14px;background:var(--good-dim);display:flex;align-items:center;justify-content:center;margin:0 auto 16px;"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--good)" stroke-width="2.6"><path d="M20 6L9 17l-5-5"></path></svg></div><h1 style="margin:0 0 6px;font-size:24px;font-weight:600;">You won the block</h1><p style="margin:0 0 26px;font-size:13.5px;color:var(--dim);">The asset has been delivered to you in exchange for the price you paid — settled atomically.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;text-align:left;"><div class="panel" style="padding:22px;"><div class="caps" style="margin-bottom:8px;">You paid</div><div class="mono" style="font-size:28px;font-weight:600;color:var(--good-text);">${d.myBidFmt}</div></div><div class="panel" style="padding:22px;"><div class="caps" style="margin-bottom:8px;">Asset received</div><div style="font-size:16px;font-weight:600;margin-bottom:6px;">T-Bill block</div><div class="mono" style="font-size:13px;color:var(--dim);">${d.faceFmt} face</div></div></div></div>`;
  if(d.myIsLoser) return `<div style="max-width:680px;margin:10px auto 0;text-align:center;"><div style="width:52px;height:52px;border-radius:14px;background:var(--panel);border:1px solid var(--line2);display:flex;align-items:center;justify-content:center;margin:0 auto 16px;"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--dim)" stroke-width="2"><path d="M5 12h14"></path></svg></div><h1 style="margin:0 0 6px;font-size:24px;font-weight:600;">Not awarded</h1><p style="margin:0 0 26px;font-size:13.5px;color:var(--dim);">This block cleared to another counterparty. Your escrow has been returned in full.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;text-align:left;"><div class="panel" style="padding:22px;"><div class="caps" style="margin-bottom:8px;">Escrow returned</div><div class="mono" style="font-size:28px;font-weight:600;">${d.myEscrowFmt}</div><div style="margin-top:6px;font-size:12px;color:var(--good-text);">Released in full ✓</div></div><div class="hatch" style="border-radius:12px;padding:22px;display:flex;flex-direction:column;justify-content:center;"><div class="caps" style="margin-bottom:10px;">Winning price</div><div style="display:flex;align-items:center;gap:11px;">${LOCK('var(--faint)',18)}<span class="mono" style="font-size:16px;font-weight:600;color:var(--dim);letter-spacing:.08em;">••••••••</span></div><div style="margin-top:10px;font-size:12px;color:var(--faint);line-height:1.45;">Not disclosed to you. The cleared price is need-to-know between the seller and the winner.</div></div></div></div>`;
  return `<div style="text-align:center;margin-top:40px;"><h1 style="margin:0 0 6px;font-size:22px;font-weight:600;">No bid on this block</h1><p style="margin:0;font-size:13.5px;color:var(--dim);">You did not submit a bid, so there is no outcome to report. The cleared price is not disclosed to you.</p></div>`;
}
